# Generated by Django 6.0.7 on 2026-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(default='Kit Dev Pro', max_length=200, verbose_name='Produto')),
                ('comprador_nome', models.CharField(max_length=200, verbose_name='Nome do comprador')),
                ('comprador_email', models.EmailField(max_length=254, verbose_name='E-mail do comprador')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reembolsada', 'Reembolsada'), ('cancelada', 'Cancelada')], default='aprovada', max_length=20, verbose_name='Status')),
                ('plataforma', models.CharField(choices=[('kiwify', 'Kiwify'), ('hotmart', 'Hotmart'), ('stripe', 'Stripe'), ('manual', 'Registro Manual')], default='kiwify', max_length=20, verbose_name='Plataforma')),
                ('referencia_externa', models.CharField(blank=True, help_text='ID da transação na plataforma de pagamento', max_length=200, verbose_name='Referência externa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da compra')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
