# Generated by Django 6.0.7 on 2026-07-29 18:28

from django.db import migrations, models


def limpar_referencias_vazias(apps, schema_editor):
    """
    Converte referencia_externa='' para NULL antes do unique= ser aplicado —
    MySQL trata strings vazias como valores normais (colidem no índice único),
    mas permite múltiplos NULLs, que é o que queremos para compras manuais
    sem ID de plataforma.
    """
    Compra = apps.get_model('core', 'Compra')
    Compra.objects.filter(referencia_externa='').update(referencia_externa=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # Passo 1: permite NULL antes de tornar único, sem quebrar linhas
        # existentes com referencia_externa='' (múltiplas '' violariam o
        # unique= aplicado diretamente).
        migrations.AlterField(
            model_name="compra",
            name="referencia_externa",
            field=models.CharField(
                blank=True,
                help_text="ID da transação na plataforma de pagamento",
                max_length=200,
                null=True,
                verbose_name="Referência externa",
            ),
        ),
        migrations.RunPython(limpar_referencias_vazias, migrations.RunPython.noop),
        # Passo 2: agora sim aplica o unique=, com nenhuma linha em '' restante.
        migrations.AlterField(
            model_name="compra",
            name="referencia_externa",
            field=models.CharField(
                blank=True,
                help_text="ID da transação na plataforma de pagamento",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Referência externa",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovada", "Aprovada"),
                    ("reembolsada", "Reembolsada"),
                    ("cancelada", "Cancelada"),
                ],
                db_index=True,
                default="aprovada",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
