# Generated by Django 6.0.7 on 2026-08-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_compra_referencia_externa_alter_compra_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome / Empresa"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "tipos_projeto",
                    models.CharField(max_length=255, verbose_name="Tipos de Projeto"),
                ),
                ("prazo", models.CharField(max_length=50, verbose_name="Prazo")),
                ("suporte", models.CharField(max_length=50, verbose_name="Suporte")),
                ("descricao", models.TextField(verbose_name="Descrição do Projeto")),
                (
                    "atendido",
                    models.BooleanField(
                        default=False, verbose_name="Atendido/Respondido"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Envio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Orçamento",
                "verbose_name_plural": "Solicitações de Orçamento",
                "ordering": ["-criado_em"],
            },
        ),
    ]
