# Generated by Django 6.0.7 on 2026-07-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(db_index=True, default='geral', max_length=50)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('texto', models.CharField(max_length=500, verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['criado_em'],
            },
        ),
    ]
