# Generated by Django 6.0.7 on 2026-08-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Curso"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "icone",
                    models.CharField(
                        default="🐍",
                        help_text="Emoji ou classe de ícone: 🐍, ⚡, 🤖",
                        max_length=50,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("iniciante", "Iniciante"),
                            ("intermediario", "Intermediário"),
                            ("avancado", "Avançado"),
                        ],
                        default="iniciante",
                        max_length=20,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Licao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título da Lição"),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("duracao_minutos", models.PositiveIntegerField(default=5)),
            ],
            options={
                "verbose_name": "Lição",
                "verbose_name_plural": "Lições",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("slide", "Slide Explicativo (Teoria)"),
                            ("quiz", "Múltipla Escolha (Quiz)"),
                            ("code", "Completar Código"),
                        ],
                        default="slide",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=250)),
                (
                    "conteudo",
                    models.TextField(
                        blank=True, help_text="Texto explicativo ou instruções"
                    ),
                ),
                ("imagem_url", models.URLField(blank=True, null=True)),
                ("pergunta", models.CharField(blank=True, max_length=300)),
                (
                    "opcoes_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de strings para as opções",
                    ),
                ),
                ("resposta_correta", models.CharField(blank=True, max_length=250)),
                (
                    "nome_arquivo",
                    models.CharField(blank=True, default="script.py", max_length=50),
                ),
                ("dica", models.CharField(blank=True, max_length=200)),
                (
                    "licao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="cursos.licao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa da Lição",
                "verbose_name_plural": "Etapas da Lição",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Módulo"),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="cursos.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "ordering": ["ordem"],
            },
        ),
        migrations.AddField(
            model_name="licao",
            name="modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licoes",
                to="cursos.modulo",
            ),
        ),
    ]
