# Generated by Django 6.0.7 on 2026-08-05 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressoLicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=100)),
                ("concluida", models.BooleanField(default=True)),
                ("data_conclusao", models.DateTimeField(auto_now_add=True)),
                (
                    "licao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to="cursos.licao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Lição",
                "verbose_name_plural": "Progressos de Lições",
                "unique_together": {("session_key", "licao")},
            },
        ),
    ]
