# Generated by Django 6.0.7 on 2026-08-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0002_progressolicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="licao",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição da Lição"),
        ),
        migrations.AddField(
            model_name="licao",
            name="icone",
            field=models.CharField(
                default="🎯",
                help_text="Emoji ou símbolo do tópico: 🐍, ⚡, 🎯, 🧠, ⚙️",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição do Módulo"),
        ),
        migrations.AddField(
            model_name="modulo",
            name="icone",
            field=models.CharField(
                default="📌",
                help_text="Emoji ou símbolo do capítulo: 🐍, 🧱, ⚡, 🤖, 💾",
                max_length=50,
            ),
        ),
    ]
