# Generated by Django 6.0.7 on 2026-07-15 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_habilidades_csv_para_modelo(apps, schema_editor):
    """Converte o texto livre 'habilidades' (CSV) de cada perfil em registros
    do novo modelo Habilidade, antes que a coluna antiga seja descartada.
    """
    PerfilUsuario = apps.get_model('accounts', 'PerfilUsuario')
    Habilidade = apps.get_model('accounts', 'Habilidade')

    for perfil in PerfilUsuario.objects.exclude(habilidades__isnull=True).exclude(habilidades=''):
        nomes = [s.strip()[:100] for s in perfil.habilidades.split(',') if s.strip()]
        for nome in nomes:
            Habilidade.objects.get_or_create(
                usuario=perfil,
                nome=nome,
                defaults={'categoria': 'linguagem', 'nivel': 2},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # CreateModel precisa vir antes do RunPython (que grava Habilidade),
        # e o RunPython precisa vir antes do RemoveField (que apaga a coluna
        # de onde os dados são lidos) — essa ordem preserva os dados
        # existentes em vez de descartá-los silenciosamente.
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('banco', 'Banco de Dados'), ('cloud', 'Cloud/DevOps'), ('ferramenta', 'Ferramenta')], default='linguagem', max_length=20)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Já explorei'), (2, 'Estudando'), (3, 'Domino bem')], default=2, verbose_name='Nível de confiança')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', '-nivel', 'nome'],
            },
        ),
        migrations.RunPython(migrar_habilidades_csv_para_modelo, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='habilidades',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='filosofia',
            field=models.TextField(blank=True, help_text='O que você busca, como trabalha. Ex: "Quero resolver problemas de negócio usando tecnologia..."', max_length=600, verbose_name='Minha filosofia'),
        ),
    ]
