# Generated by Django 6.0.7 on 2026-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_categorias_trilha_estudos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="aprovado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="publicado",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
