# Generated by Django 6.0.7 on 2026-07-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('autor_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('autor_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('conteudo', models.TextField(max_length=3000, verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=True, verbose_name='Visível publicamente')),
                ('fixado', models.BooleanField(default=False, verbose_name='Fixado no topo')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['-fixado', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('autor_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('conteudo', models.TextField(max_length=2000, verbose_name='Resposta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=True, verbose_name='Visível publicamente')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='comunidade.topico')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['data_criacao'],
            },
        ),
    ]
