# Generated by Django 6.0.7 on 2026-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comunidade", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resposta",
            name="aprovado",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Visível publicamente"
            ),
        ),
        migrations.AlterField(
            model_name="topico",
            name="aprovado",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Visível publicamente"
            ),
        ),
    ]
