# Generated by Django 6.0.7 on 2026-07-15 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao_curta', models.TextField(max_length=300, verbose_name='Descrição curta')),
                ('descricao_completa', models.TextField(verbose_name='Descrição completa')),
                ('categoria', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('data', 'Análise de Dados'), ('automacao', 'Automação'), ('outro', 'Outro')], default='web', max_length=20)),
                ('imagem_principal', models.ImageField(upload_to='projetos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('link_demo', models.URLField(blank=True, null=True, verbose_name='Link demo')),
                ('link_github', models.URLField(blank=True, null=True, verbose_name='Link GitHub')),
                ('tecnologias', models.CharField(help_text='Separe por vírgulas: Python,Django,MySQL', max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque na home')),
                ('publico', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/galeria/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.projeto')),
            ],
            options={
                'verbose_name': 'Imagem do projeto',
                'verbose_name_plural': 'Imagens dos projetos',
            },
        ),
    ]
