# Generated by Django 6.0.7 on 2026-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('pessoal', 'Projeto Pessoal'), ('academico', 'Projeto Acadêmico'), ('fork', 'Fork de Open Source')], default='pessoal', max_length=20, verbose_name='Tipo de projeto'),
        ),
    ]
