# Generated by Django 6.0.7 on 2026-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_projeto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="publico",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Publicado"
            ),
        ),
    ]
